### ISSUE TITLE
Request access for adidas

### ISSUE THREAD

**Issue by deichten** [cncf/enduser-public#9]
Submit this issue to request access to the End User Community

* Private repo (https://github.com/cncf/enduser)
* #enduser Slack channel
* Mailing list and meeting invitations.

Your organization must be a member of End User Community (https://www.cncf.io/people/end-user-community/), but unlimited number of people from your organization can access the community channels.

Organization name: adidas AG

Github usernames:
1. deichten
2. fernicorni

Email addresses:
1. daniel.eichten@adidas.com
2. fernando.cornago@adidas.com

**Comment by oicheryl** [comment]
Sent invitation.
